<?php include('menu.php'); ?>


<!--- Image Slider -->
<div id="slides" class="carousel slide" data-ride="carousel">
	<ul class="carousel-indicators">
		<li data-target="#slides" data-slide-to="0" class="active"></li>
		<li data-target="#slides" data-slide-to="1"></li>
		<li data-target="#slides" data-slide-to="2"></li>
	</ul>
	<div class="carousel-inner">
		
		<div class="carousel-item active">
			<img src="img/img1.jpg" alt="first slide">
			<div class="carousel-caption">
				<h1 class="display-2">Welcome to,<br>Grequo</h1>
				<h3>-Platform for EV Enthusiasts</h3>
				<div class="qu"><marquee><q>Think, Wonder, Imagine, Inspire</q></marquee></div>
				<!--<button type="button" class="btn btn-outline-light btn=lg">View our works</button>-->
				
			</div>
		</div>
		<div class="carousel-item">
			<img src="img/img2.jpg" alt="Second slide">
		</div>
		<div class="carousel-item">
			<img src="img/img3.jpg" alt="Third slide">
		</div>
		<a class="carousel-control-prev" href="#slides" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		  </a>
		  <a class="carousel-control-next" href="#slides" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
	</a>	
	
</div>
</div>
<!--- Jumbotron -->
<div class="container-fluid">
	<div class="row jumbotron">
		<div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 col-xl-10">
			<p class="lead">Please, Feel free to post your Question and Answers. We are here to clarify your Doubts.</p>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-2">
			<a href="QA forum/index.php" ><button type="button" class="btn btn-outline-secondary btn-lg">Q&A forum
          </button></a>
		</div>
	</div>
</div>


<!--- Welcome Section -->
<div class="container-fluid padding">
	<div class="row welcome text-center">
		<div class="col-12">
			<h1 class="display-4">Get your Doubt's cleared!</h1>
		</div>
		<hr>
		<div class="col-12">
			<p class="lead">Grequo is a question and answer website where people go to find information
about EVs, Every piece of content on the site is generated by users, meaning it is
created, edited, and organized by the same people that use the website. </p>
		</div>
	</div>
</div>

<!--- Connect -->
<?php include('footer.php'); ?>
<div class="logout">
 <?php echo "<h1>Thankyou for Visiting, " . $_SESSION['username'] . "</h1>"; ?>
 </div>
